# Generated by Django 4.0 on 2021-12-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_cod', models.CharField(max_length=200, unique=True, verbose_name='Codigo Identificacion')),
                ('event_nom', models.CharField(max_length=200, verbose_name='Nombre del Evento')),
                ('event_date_init', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('even_date_end', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalizacion')),
                ('event_site', models.TextField(blank=True, max_length=500, null=True, verbose_name='Lugar del Evento')),
                ('event_url', models.URLField(blank=True, null=True, verbose_name='Pagina Web')),
            ],
        ),
    ]
