# Generated by Django 4.0 on 2021-12-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_code', models.CharField(max_length=200, unique=True, verbose_name='Codigo del Libro')),
                ('book_name', models.CharField(max_length=200, verbose_name='Nombre del Libro')),
                ('book_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Publicación')),
                ('book_cenditel', models.BooleanField(verbose_name='Realizado en CENDITEL?')),
                ('book_url', models.URLField(blank=True, null=True, verbose_name='Pagina Web')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=200, unique=True, verbose_name='Codigo del Curso')),
                ('course_name', models.CharField(max_length=200, verbose_name='Nombre del Curso')),
                ('course_date_init', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('course_date_end', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magazine_code', models.CharField(max_length=200, unique=True, verbose_name='Cidigo de la Revista')),
                ('magazine_name', models.CharField(max_length=200, verbose_name='Nombre de la Revista')),
                ('magazine_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Publicacion')),
                ('magazine_arb', models.BooleanField(verbose_name='Registra Arbitrada?')),
                ('magazine_cenditel', models.BooleanField(verbose_name='Realizada en CENDITEL?')),
                ('magazine_url', models.URLField(blank=True, null=True, verbose_name='Pagina Web')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_code', models.CharField(max_length=10, unique=True, verbose_name='Codigo del Participante')),
                ('participant_document', models.CharField(max_length=200, unique=True, verbose_name='Cedula de Identidad')),
                ('participant_name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('participant_lastname', models.CharField(max_length=200, verbose_name='Apellido')),
                ('participant_email', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=200, unique=True, verbose_name='Codigo del Proyecto')),
                ('project_name', models.CharField(max_length=200, verbose_name='Nombre del Proyecto')),
                ('project_date_init', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('project_date_end', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalizacion')),
                ('project_poa', models.BooleanField(verbose_name='Pertenece al POA?')),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('researcher_code', models.CharField(max_length=10, unique=True, verbose_name='Codigo del Participante')),
                ('researcher_document', models.CharField(max_length=200, unique=True, verbose_name='Cedula de Identidad')),
                ('researcher_name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('researcher_lastname', models.CharField(max_length=200, verbose_name='Apellido')),
                ('reseracher_active', models.BooleanField(verbose_name='Se encuentra activo?')),
            ],
        ),
    ]
